### ISSUE TITLE
ESM file cannot be loaded by `require`

### ISSUE THREAD

**Issue by GoToBoy** [ivesia/vite-plugin-rewrite-all#5]
vite.config.js:5:29:
      5 │ import pluginRewriteAll from 'vite-plugin-rewrite-all';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/esbuild/lib/main.js:1374:27: ERROR: [plugin: externalize-deps] "vite-plugin-rewrite-all" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
    at failureErrorWithLog (E:\lachesis\whiteboard\meepo\node_modules\esbuild\lib\main.js:1650:15)
    at E:\lachesis\whiteboard\meepo\node_modules\esbuild\lib\main.js:1059:25
    at runOnEndCallbacks (E:\lachesis\whiteboard\meepo\node_modules\esbuild\lib\main.js:1485:45)
    at buildResponseToResult (E:\lachesis\whiteboard\meepo\node_modules\esbuild\lib\main.js:1057:7)
    at E:\lachesis\whiteboard\meepo\node_modules\esbuild\lib\main.js:1086:16
    at responseCallbacks.<computed> (E:\lachesis\whiteboard\meepo\node_modules\esbuild\lib\main.js:703:9)
    at handleIncomingPacket (E:\lachesis\whiteboard\meepo\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (E:\lachesis\whiteboard\meepo\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)

**Comment by GoToBoy** [comment]
i know what's problem

**Comment by tkamstra** [comment]
@GoToBoy what was your fix?
